# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    dbpass:
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 5
aws:
  s3:
    bucketName: world-weather
    accessKey: S3-ACCESS-DEV
    secretKey: S3-SECRET-DEV
